### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by IvanRodriCalleja** [IvanRodriCalleja/swc-viewer#22]
- [ ] Add support for linux
- [ ] Add support for windows
- [ ] Add support for local @swc/core transformation (mainly for SWC developers)
- [ ] Add support for folder tree
- [ ] Add support for open folder with CLI
- [ ] Add support for AST comparison
- [ ] Add support for diff editor
- [ ] Add support for global config
- [ ] Add support for test compare execution
